function GTensionComp(X1, Y1, X2, Y2)
%CREATEFIGURE(X1, Y1, X2, Y2)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data

%  Auto-generated by MATLAB on 07-Jun-2018 05:18:16

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'DisplayName','10C-Tensión salida SPM','Color',[1 0 0]);

% Create plot
plot(X2,Y2,'DisplayName','10C-Tensión salida Tres-parámetros',...
    'Color',[0 0 1]);

% Create xlabel
xlabel('Tiempo, t [s]');

% Create title
title('Comparación de tensiones SPM y Tres-parámetros');

% Create ylabel
ylabel('Tensión, V [V]');

box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',14);
% Create legend
legend(axes1,'show');

