function Surf_cp(xdata1, ydata1, zdata1)
%CREATEFIGURE(XDATA1, YDATA1, ZDATA1)
%  XDATA1:  surface xdata
%  YDATA1:  surface ydata
%  ZDATA1:  surface zdata

%  Auto-generated by MATLAB on 07-Jun-2018 16:21:07

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create surf
surf(xdata1,ydata1,zdata1,'Parent',axes1);

% Create xlabel
xlabel('Distance, r [cm]');

% Create zlabel
zlabel('Concentration^+, c_{s} [mol*m^{-3}]');

% Create title
title('Concentration electrode^{+}');

% Create ylabel
ylabel('Time, t [s]');

view(axes1,[-37.5 30]);
grid(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',14);
